export  const data = [
    {
      id:1,
      nombre:"Roas beef",
      stock:20,
      tipo: "Carne vacuna",
      descripcion: "El roast beef es un corte de buey tierno que se asa al horno. En la cocina inglesa, y por extensión en muchos países de tradición anglosajona como Australia, el roast beef es un plato muy tradicional, servido preferentemente los domingos.",
      cocccion: "Cacerola, horno y plancha",
      precio: 1150,
      img: 'https://static.diariovasco.com/www/multimedia/201906/03/media/cortadas/carne-roja-kS1C-R5uqUSGFlSqj84mn1I9bQuN-624x385@Diario%20Vasco.jpg',
    },
    {
      id:2,
      nombre:"Asado",
      stock:10,
      tipo: "Carne vacuna",
      descripcion: "Uno de los cortes de carne más populares para el asado es el llamado asado de tira, que también se conoce como tira de asado. Se trata del costillar de la vaca, cortado transversalmente.",
      cocccion: "Cacerola, horno y plancha",
      precio: 1250,
      img: 'https://assets.iprofesional.com/cdn-cgi/image/w=880,f=webp/https://assets.iprofesional.com/assets/jpg/2021/11/527470.jpg',
    },
    {
      id:3,
      nombre:"Bondiola",
      stock:20,
      tipo: "Carne porcina",
      descripcion: "Uno de los cortes de carne más populares para el asado es el llamado asado de tira, que también se conoce como tira de asado. Se trata del costillar de la vaca, cortado transversalmente.",
      cocccion: "Cacerola, horno y plancha",
      precio: 850,
      img: 'https://elgourmet.s3.amazonaws.com/recetas/cover/bondi_WV2YC6bQEuTpRmkF79rBAKHZhzoa4v.png',
    },
    {
      id:4,
      nombre:"Pollo",
      stock:50,
      tipo: "Carne de ave",
      descripcion: "Uno de los cortes de carne más populares para el asado es el llamado asado de tira, que también se conoce como tira de asado. Se trata del costillar de la vaca, cortado transversalmente.",
      cocccion: "Cacerola, horno y plancha",
      precio: 350,
      img: 'https://www.paulinacocina.net/wp-content/uploads/2021/11/pollo-asado.jpg',
    },
    {
      id: 5,
      nombre:"Bife de chorizo",
      stock: 15,
      tipo: "Carne vacuna",
      descripcion: "Uno de los cortes de carne más populares para el asado es el llamado asado de tira, que también se conoce como tira de asado. Se trata del costillar de la vaca, cortado transversalmente.",
      cocccion: "Cacerola, horno y plancha",
      precio: 1850,
      img: 'https://static.diariovasco.com/www/multimedia/201906/03/media/cortadas/carne-roja-kS1C-R5uqUSGFlSqj84mn1I9bQuN-624x385@Diario%20Vasco.jpg',
   },
  ];